FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        software-properties-common \
        python3.11 \
        python3-pip \
        python3-apt \
        python3.11-dev \
        cmake \
        make \
        libgsl-dev \
        git \
        curl \
        g++ && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

    ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8
ENV PYTHONUNBUFFERED=1

WORKDIR /app
COPY . .
RUN rm -rf build TDA.egg-info
RUN python3.11 -m pip install --no-cache-dir --upgrade pip setuptools wheel
RUN python3.11 -m pip install --no-cache-dir --break-system-packages --ignore-installed .
EXPOSE 8000

HEALTHCHECK --interval=30s --timeout=10s --start-period=10s --retries=3 \
    CMD curl -f http://localhost:8000/health || exit 1

CMD ["python3.11", "main.py"]
